### ISSUE TITLE
5.3更新后不能进本

### ISSUE THREAD

**Issue by idenpa** [athlon18/RBtrust#2]
5.3更新之后，加载脚本开始后会出现多玛方桌战的设置选项，而不是亲信战友的相关操作，需要手动操作进本才行，进本之后打本正常。

**Comment by incubator4** [comment]
尝试一下搜索下<CodeChunk name="选择副本">这个标题然后，下面有个
```
					#if RB_CN
							var Id = 319;
					#else
							var Id = 314;
					#endif
					AgentModule.ToggleAgentInterfaceById(Id);
```
把314改成319

**Comment by idenpa** [comment]
> 尝试一下搜索下这个标题然后，下面有个
> 
> ```
> 					#if RB_CN
> 							var Id = 319;
> 					#else
> 							var Id = 314;
> 					#endif
> 					AgentModule.ToggleAgentInterfaceById(Id);
> ```
> 
> 把314改成319

已经搞定 感谢~
